const asyncHandler = require('express-async-handler');
const prisma = require('../config/db');
const formatResponse = require('../utils/formatResponse');
const { sendLessonNoteEmail } = require('../utils/emailService');

const parseNote = (note) => {
    return {
        ...note,
        references: note.references ? JSON.parse(note.references) : [],
        objectives: note.objectives ? JSON.parse(note.objectives) : [],
        instructionalMaterials: note.instructionalMaterials ? JSON.parse(note.instructionalMaterials) : [],
        presentation: note.presentation ? JSON.parse(note.presentation) : [],
        evaluation: note.evaluation ? JSON.parse(note.evaluation) : [],
    };
};

// @desc    Create a lesson note
// @route   POST /api/notes
// @access  Private
const { createUsageLog, checkWeeklyLessonLimit } = require('../utils/usage');

const createNote = asyncHandler(async (req, res) => {
    const {
        topic, subtopic, classLevel, subject, duration, date,
        references, objectives, instructionalMaterials, previousKnowledge,
        introduction, lessonContent, presentation, evaluation, assignment, conclusion
    } = req.body;

    // If this note is an AI-generated note, enforce dynamic limits
    if (req.body && req.body.generatedByAI) {
        const canGen = await usageService.canGenerateLesson(req.user.id);
        if (!canGen.canGenerate) {
            res.status(403);
            return res.json(formatResponse(false, canGen.reason));
        }
    }

    // Check for duplicates before creating
    const existingNote = await prisma.lessonNote.findFirst({
        where: {
            userId: req.user.id,
            topic,
            subtopic: subtopic || "",
            classLevel,
            subject,
            lessonContent: lessonContent || undefined
        }
    });

    if (existingNote) {
        return res.status(200).json(formatResponse(true, 'Already saved', parseNote(existingNote)));
    }

    const note = await prisma.lessonNote.create({
        data: {
            userId: req.user.id,
            topic, subtopic, classLevel, subject, duration,
            date: (date && !isNaN(new Date(date).getTime())) ? new Date(date) : undefined,
            references: references ? JSON.stringify(references) : '[]',
            objectives: objectives ? JSON.stringify(objectives) : '[]',
            instructionalMaterials: instructionalMaterials ? JSON.stringify(instructionalMaterials) : '[]',
            previousKnowledge, introduction, lessonContent,
            presentation: presentation ? JSON.stringify(presentation) : '[]',
            evaluation: evaluation ? JSON.stringify(evaluation) : '[]',
            assignment, conclusion
        }
    });

    // If the request indicates this note was generated by AI, create a usage log
    // so we can track AI generation uses. Frontend may provide `generatedByAI: true`.
    try {
        if (req.body && req.body.generatedByAI) {
            await createUsageLog(req.user.id, 'LESSON_GENERATION');
        }
    } catch (err) {
        // Don't fail the request if logging fails
        console.error('Usage log failed:', err);
    }

    res.status(201).json(formatResponse(true, 'Lesson note created', parseNote(note)));
});

// @desc    Get user lesson notes
// @route   GET /api/notes
// @access  Private
const getNotes = asyncHandler(async (req, res) => {
    const notes = await prisma.lessonNote.findMany({
        where: { userId: req.user.id },
        orderBy: { createdAt: 'desc' }
    });

    // Parse JSON fields for each note
    const parsedNotes = notes.map(parseNote);

    res.json(formatResponse(true, 'Lesson notes retrieved', parsedNotes));
});

// @desc    Get single lesson note
// @route   GET /api/notes/:id
// @access  Private
const getNoteById = asyncHandler(async (req, res) => {
    const note = await prisma.lessonNote.findUnique({
        where: { id: req.params.id }
    });

    if (note && note.userId === req.user.id) {
        res.json(formatResponse(true, 'Lesson note retrieved', parseNote(note)));
    } else {
        res.status(404);
        throw new Error('Note not found');
    }
});

// @desc    Delete lesson note
// @route   DELETE /api/notes/:id
// @access  Private
const deleteNote = asyncHandler(async (req, res) => {
    const note = await prisma.lessonNote.findUnique({ where: { id: req.params.id } });

    if (note && note.userId === req.user.id) {
        await prisma.lessonNote.delete({ where: { id: req.params.id } });
        res.json(formatResponse(true, 'Lesson note deleted'));
    } else {
        res.status(404);
        throw new Error('Note not found');
    }
});

// @desc    Email lesson note to user
// @route   POST /api/notes/:id/email
// @access  Private
const emailNote = asyncHandler(async (req, res) => {
    const note = await prisma.lessonNote.findUnique({ where: { id: req.params.id } });

    if (note && note.userId === req.user.id) {
        const parsedNote = parseNote(note);
        const success = await sendLessonNoteEmail(req.user.email, parsedNote);

        if (success) {
            res.json(formatResponse(true, 'Lesson note sent to your email'));
        } else {
            res.status(500);
            throw new Error('Failed to send email. Please check your SMTP settings.');
        }
    } else {
        res.status(404);
        throw new Error('Note not found');
    }
});

module.exports = {
    createNote,
    getNotes,
    getNoteById,
    deleteNote,
    emailNote,
};
